//------------------------------------------------------------------------------
// <auto-generated>
//     Koden er generert av et verktøy.
//     Kjøretidsversjon:4.0.30319.42000
//
//     Endringer i denne filen kan føre til feil virkemåte, og vil gå tapt hvis
//     koden genereres på nytt.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace D365.Demo.Transform.D365 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Document {
        
        private EcoResProductV2Entity[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ECORESPRODUCTV2ENTITY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EcoResProductV2Entity[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class EcoResProductV2Entity {
        
        private string pRODUCTCOLORGROUPIDField;
        
        private string pRODUCTDESCRIPTIONField;
        
        private string pRODUCTDIMENSIONGROUPNAMEField;
        
        private string pRODUCTNAMEField;
        
        private string pRODUCTNUMBERField;
        
        private string pRODUCTSEARCHNAMEField;
        
        private string pRODUCTSIZEGROUPIDField;
        
        private string pRODUCTSTYLEGROUPIDField;
        
        private string pRODUCTSUBTYPEField;
        
        private string pRODUCTTYPEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTCOLORGROUPID {
            get {
                return this.pRODUCTCOLORGROUPIDField;
            }
            set {
                this.pRODUCTCOLORGROUPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTDESCRIPTION {
            get {
                return this.pRODUCTDESCRIPTIONField;
            }
            set {
                this.pRODUCTDESCRIPTIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTDIMENSIONGROUPNAME {
            get {
                return this.pRODUCTDIMENSIONGROUPNAMEField;
            }
            set {
                this.pRODUCTDIMENSIONGROUPNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTNAME {
            get {
                return this.pRODUCTNAMEField;
            }
            set {
                this.pRODUCTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTNUMBER {
            get {
                return this.pRODUCTNUMBERField;
            }
            set {
                this.pRODUCTNUMBERField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTSEARCHNAME {
            get {
                return this.pRODUCTSEARCHNAMEField;
            }
            set {
                this.pRODUCTSEARCHNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTSIZEGROUPID {
            get {
                return this.pRODUCTSIZEGROUPIDField;
            }
            set {
                this.pRODUCTSIZEGROUPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTSTYLEGROUPID {
            get {
                return this.pRODUCTSTYLEGROUPIDField;
            }
            set {
                this.pRODUCTSTYLEGROUPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTSUBTYPE {
            get {
                return this.pRODUCTSUBTYPEField;
            }
            set {
                this.pRODUCTSUBTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PRODUCTTYPE {
            get {
                return this.pRODUCTTYPEField;
            }
            set {
                this.pRODUCTTYPEField = value;
            }
        }
    }
}
